replicaCount: 2

image:
  repository: ""
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

ingress:
  enabled: true

  className: alb

  scheme: internet-facing

  targetType: ip

  path: /

  pathType: Prefix
