apiVersion: apps/v1
kind: Deployment

metadata:
  name: sample-war

  labels:
    app: sample-war

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: sample-war

  template:
    metadata:
      labels:
        app: sample-war

    spec:
      containers:

        - name: sample-war

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /hello-world/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /hello-world/
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
