apiVersion: v1
kind: Service

metadata:
  name: sample-war

  labels:
    app: sample-war

spec:
  type: {{ .Values.service.type }}

  selector:
    app: sample-war

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
